version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      action-deps:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go-deps:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      docker-base-images:
        patterns:
          - "*"